Move IDocument implementation to Core library
Azure/azure-functions-openapi-extension pull request #278
Opened 2021-10-12 23:16 UTC by MikeChristensen

We have the desire to use `Microsoft.Azure.WebJobs.Extensions.OpenApi.Core`, but don't want to use `Microsoft.Azure.WebJobs.Extensions.OpenApi` since we want to implement our own IFunctionProvider and various routes.  We can do this, but we basically have to copy the implementation of `IDocument` which seems unnecessary.  It would be better if `Document` was part of the  Core library, as Document doesn't appear to have any other dependencies on `Microsoft.Azure.WebJobs.Extensions.OpenApi` anyway.

2021-10-14 06:12 UTC, justinyoo commented
> What's funny is I can move both `IDocument` implementations to core, and it compiles and all unit tests even pass, but the Swagger doc comes up empty.

We need to have more unit test coverage for the `Document` class, which is one of our improving points.

> I'll dig into it a bit more and see what I can come up with.. Hoping we can DRY it out a bit..

Yes, let's find some points for DRY.

2021-10-15 01:43 UTC, MikeChristensen commented
@justinyoo So, honestly the only differences between the two `DocumentHelperExtension` classes is the Worker stuff looks for `Microsoft.Azure.Functions.Worker.FunctionAttribute` attributes and the legacy stuff looks for `Microsoft.Azure.WebJobs.FunctionNameAttribute` (The `HttpTriggerAttribute` classes are different as well).  Really none of the actual logic is different, which got me thinking this is more of a build problem, and not a code problem.  I've been playing with another approach, which I think looks promising.

# Changes

`Microsoft.Azure.WebJobs.Extensions.OpenApi.Core` now targets both `netstandard20` and `net50`

This will let us share the same `DocumentHelperExtensions` for both target frameworks.  Since the Linq expression in `GetHttpTriggerMethods` looks for different types, we can use some compile-time conditional logic to grab the correct methods.

This lets us get rid of a bunch of code in the `Worker.Extensions.OpenApi` project that was redundant with the core stuff, such as `DocumentHelperExtension`, `FunctionAttributeExtentions`, `HttpTriggerAttributeExtensions`, etc.  Also, the unit tests for those things can go as well.

Also, the unit tests can target both frameworks which will let us share a lot of testing logic across both frameworks.  This might eventually let us get rid of the `Worker.Extensions.OpenApi.Tests` project at some point and combine everything into one.

Let me know what you think.  I tested various sample projects and made sure the `/swagger.json` endpoint generates everything correctly, and all unit tests pass.

2021-11-08 05:59 UTC, justinyoo requested changes
Thanks for the suggestion! I like the idea because it was my first approach to try. But at the end of the day, I had to give up this approach &ndash; supporting both .NET Standard 2.0 and .NET 5 at the core level because .NET Standard is a spec, and .NET Core 3.1, .NET 5 and .NET 6 are implementations.

We might need a different approach.

2021-11-08 05:59 UTC, justinyoo commented on src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Extensions/DocumentHelperExtensions.cs
> +#if NET5_0
This was my first approach. But, it might become the issue when .NET 6, .NET 7, etc keep coming.

2022-02-25 07:47 UTC, justinyoo commented
Since #344 looks more promising, I'll close this PR. Thanks for your patience!

2022-02-25 07:47 UTC, closed without merging