Only add unique openApiReferenceIds to the exported types
Azure/azure-functions-openapi-extension pull request #424
Opened 2022-04-22 08:51 UTC by Arjan321

Multiple types might be used for both input and output, getting the same openApiReferenceId.

This PR makes sure only the first openApiReference gets added. Fixes #407

2022-04-22 08:59 UTC, rlucassen approved these changes

2022-04-27 22:37 UTC, justinyoo requested changes
@Arjan321 Oh, thanks for the PR! Would you be able to add test methods to support your changes?

2022-04-28 11:35 UTC, Arjan321 commented
> @Arjan321 Oh, thanks for the PR! Would you be able to add test methods to support your changes?

@justinyoo added a test!

2022-04-29 01:55 UTC, justinyoo approved these changes
Thanks for the change! LGTM

2022-04-29 01:56 UTC, merged