add TimeSpanObjectTypeVisitor
Azure/azure-functions-openapi-extension pull request #524
Opened 2022-12-20 16:13 UTC by sinantutan

As reported in #401 the type of TimeSpan is incorrectly displayed as a complex object. This PR aims for fixing this issue. 

We can then have a new field in our Order class of the type TimeSpan
![image](https://user-images.githubusercontent.com/73258913/208713478-3e0f4af3-8b37-4f2d-8276-b8aed5a39e72.png)

And achieve the following result
![image](https://user-images.githubusercontent.com/73258913/208713006-0c52bc03-aa43-484b-82ee-fa6fba4517b9.png)

2022-12-20 16:14 UTC, sinantutan commented
@microsoft-github-policy-service agree

2022-12-21 01:31 UTC, justinyoo requested changes
@sinantutan Thanks for your PR! I left a comment. In addition to that, would you be able to add tests for your changes, please?

2022-12-21 01:31 UTC, justinyoo commented on src/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core/Visitors/TimeSpanObjectTypeVisitor.cs
> +
This requires `IsParameterVisitable(Type type)` method to be implemented.

2022-12-21 16:57 UTC, sinantutan commented
> @sinantutan Thanks for your PR! I left a comment. In addition to that, would you be able to add tests for your changes, please?

@justinyoo many thanks for reviewing my PR. I've made the changes you requested. Please let me know if anything is missing.

2022-12-23 05:49 UTC, justinyoo approved these changes
Thanks @sinantutan for your contribution! LGTM

2022-12-23 05:49 UTC, merged