create test for OpenApiWriterFactory.cs
Azure/azure-functions-openapi-extension pull request #584
Opened 2023-05-13 17:50 UTC by JaewonB37

Describe the issue
The code above contains a test class for OpenApiWriterFactory in the Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests namespace. This class has two test methods, CreateInstance_Should_Return_Json_Writer() and CreateInstance_Should_Return_Yaml_Writer(), that check if the OpenApiWriterFactory creates the correct writer instance for the specified OpenApiFormat.

To Reproduce
To reproduce the issue, follow these steps:

1. Open the solution containing the Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests project.
2. Build the solution to ensure all dependencies are resolved.
3. Run the test class OpenApiWriterFactoryTests.
4. Observe the results of the test methods.
5. Expected behavior
6. The test methods should pass, indicating that the OpenApiWriterFactory correctly creates the writer instance for the specified OpenApiFormat.

Screenshots
N/A

Environment

OS: [Windows]
Browser [chrome]
Version [.net 7.0]
Additional context
No additional context.

2023-05-13 17:50 UTC, JaewonB37 commented
@microsoft-github-policy-service agree

2023-05-14 01:57 UTC, SoniaComp reviewed
I add several comments for your PR. Thank you for contribution 👍

2023-05-14 01:57 UTC, SoniaComp commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +        [TestMethod]
How about change this "Test Method" to "Data Test Method"?

2023-05-14 01:57 UTC, SoniaComp commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +            StringWriter writer = new StringWriter();
Please change this variable to the class private variable, and you can initialize it in the ["TestInitialize"].

2023-05-14 01:57 UTC, SoniaComp commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +            // Arrange
Could you take out this commented line and other comments like this?

2023-05-14 01:57 UTC, SoniaComp commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +            Assert.IsNotNull(result);
You can check the expected result like this. `.Should().BeOfType<OpenApiYamlWriter>();`

2023-05-14 02:37 UTC, SoniaComp commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +            result.Should().NotBeNull();
I think this line is not needed. I think It's better "One Test" for "One Method".

2023-05-14 02:37 UTC, SoniaComp reviewed
I add a comment!

2023-05-14 02:46 UTC, justinyoo requested changes

2023-05-14 02:46 UTC, justinyoo commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +            }
Each test method tests one condition. This part SHOULD utilise the `DataRow` attribute.

2023-05-14 04:18 UTC, justinyoo requested changes
Almost there!

2023-05-14 04:18 UTC, justinyoo commented on test/Microsoft.Azure.WebJobs.Extensions.OpenApi.Core.Tests/OpenApiWriterFactoryTests.cs
> +        public void Given_OpenApiFormat_When_CreateInstance_Then_Should_Return_Correct_OpenApiWriter(OpenApiFormat format, Type writerType)
Could you change the parameter name to `expected` instead of `writerType`?

2023-05-14 04:42 UTC, SoniaComp approved these changes
LGTM!

2023-05-14 04:56 UTC, justinyoo approved these changes
LGTM! Thanks for your contribution.

2023-05-14 04:56 UTC, merged